gravity-ui/markdown-editor

src/extensions/yfm/YfmCut/commands.test.ts, src/extensions/yfm/YfmCut/commands.ts, src/extensions/yfm/YfmCut/index.ts, src/extensions/yfm/YfmNote/commands.test.ts, src/extensions/yfm/YfmNote/commands.ts, src/extensions/yfm/YfmNote/index.ts
For both note and cut:
- when the cursor is at the beginning of title and you press the backspace button, the block will be replaced by its title and content
- when the cursor is at the beginning of the block content and you press the backspace button, the cursor will be moved to the end of block title
=> feat(YfmNote, YfmCut): easy removal by pressing the backspace button

src/core/markdown/Markdown.test.ts, src/core/markdown/MarkdownSerializer.js
During sterilization, we need to escape the corner brackets, because later they can be parsed as HTML
=> feat(core): escape corner brackets during serialization

src/core/ExtensionBuilder.ts, src/extensions/markdown/Breaks/index.ts, src/extensions/markdown/Html/index.ts
The key-value storage `context` has been added to the ExtensionBuilder, which allows you to transfer data between extensions.
Usage:
```ts
const builder = new ExtensionBuilder(
ExtensionBuilder.createContext()
.set('globalflag', true)
);
const Extension0: ExtensionAuto = (builder) => {
builder.context.set('someflag', true);
// ...
};
const Extension1: ExtensionAuto = (builder) => {
if (builder.context.get('globalflag') === true) {
// ...
}
if (builder.context.get('someflag') === true) {
// ...
}
};
builder.use(Extension0).use(Extension1);
```
=> feat(core): add context to extension builder

demo/Playground.scss, demo/Playground.tsx, src/common/index.ts, src/core/ContentHandler.test.ts, src/core/ContentHandler.ts, src/index.ts
1. Сontrols have been added to the Playground that allow you to perform methods of modifying the current content (append, prepend, replace, clear, etc.)
2. Added tests for content handler
3. Fixed `.append()` method: now it replaces last empty paragraph with the passed markup and, if necessary, adds an empty paragraph after
=> fix(core): when appending replace last empty paragraph with new content and add empty paragraph after

src/core/ContentHandler.test.ts, src/core/markdown/MarkdownParser.ts, src/core/types/parser.ts, src/extensions/markdown/Link/index.ts, src/extensions/markdown/Link/paste-plugin.ts
If, when pasting in the editor, the text is selected inside one textblock, and there is a URL in `event.clipboardData`, then create a link with the selected text and the inserted URL
=> feat(Link): when pasting, create a link with the pasted URL and selected text

src/core/ExtensionBuilder.test.ts, src/core/ExtensionBuilder.ts, src/extensions/markdown/Code/Code.test.ts, src/extensions/markdown/Code/index.ts
Order of marks in schema is important for prosemirror and it affects the serialization of the prosemirror-document in DOM or markdown markup. The problem occurred when `code_inline` overlapped with other marks that were in the schema after it. I added marks priority support to `ExtensionBuilder`, and set lowest priority for `code_inline`.
=> fix: correct order for inline code among other mark when serialized to DOM and markup

src/extensions/yfm/Math/index.ts
I would like to extend the behaviour of the Math plugin in my project, so I have to import MathNode, MathBlockNodeView and MathInlineNodeView. But instead of
```typescript
import { MathNode, MathBlockNodeView, MathInlineNodeView } from '@doc-tools/yfm-editor';
```
I have to write something like this:
```typescript
import { MathBlockNodeView, MathInlineNodeView } from '@doc-tools/yfm-editor/build/esm/extensions/yfm/Math/view-and-edit';
import { MathNode } from '@doc-tools/yfm-editor/build/esm/extensions/yfm/Math/const';
```
So I added export of these items.
I am not sure it is needed publish a minor update, so I named the commit like "fix" to up the patch version.
=> fix: re-export MathNode classes

src/extensions/yfm/YfmCut/index.ts, src/extensions/yfm/YfmCut/plugins/auto-open.ts
Markup for testing:
```md
before
{% cut "cut1" %}
content1
{% cut "cut2" %}
content2
{% cut "cut3" %}
content3
{% endcut %}
{% endcut %}
{% endcut %}
after
```
=> feat(YfmCut): auto openning yfm-cut if selection is inside cut's content

src/extensions/yfm/YfmCut/index.ts, src/extensions/yfm/YfmCut/nodeviews/yfm-cut-title.scss, src/extensions/yfm/YfmCut/nodeviews/yfm-cut-title.ts
Now you can open/close YfmCut by clicking on the arrow icon, but not on the title content
=> feat(YfmCut): don't open/close yfm-cut by clicking on the title

src/extensions/markdown/Blockquote/commands.ts
there is a code below that breaks when selection has depth that equals to zero when you try to call ResolvedPos.before or ResolvedPos.after for that depth. because there is no sense to check whether there is a node before or after a doc node
=> fix: blockquote button breaks when selection has 0 depth

src/extensions/yfm/YfmTabs/const.ts, src/extensions/yfm/YfmTabs/index.ts, src/extensions/yfm/YfmTabs/plugins.ts, src/extensions/yfm/YfmTabs/spec.ts, src/extensions/yfm/YfmTabs/toYfm.ts
Improvement for tabs removement behavior.
When user presses backspace in the beginning of tab title - it removes current tab and panel associated with it.
Also activating a tab next to it and panel associated with it
=> feat: improvements for tabs removement

package-lock.json, package.json, src/extensions/behavior/Clipboard/clipboard.ts, src/extensions/behavior/Cursor/GapCursorSelection.ts, src/extensions/behavior/Cursor/gapcursor.ts, src/extensions/behavior/Selection/commands.test.ts, src/extensions/behavior/Selection/commands.ts, src/extensions/behavior/Selection/index.ts, src/extensions/markdown/Link/paste-plugin.ts, src/extensions/markdown/Table/spec.ts, src/extensions/yfm/YfmCut/spec.ts, src/extensions/yfm/YfmNote/spec.ts, src/extensions/yfm/YfmTable/commands/goToNextRow.ts, src/extensions/yfm/YfmTable/spec.ts, src/extensions/yfm/YfmTabs/spec.ts, src/selection.d.ts, src/types/spec.ts, src/utils/selection.ts
I rewrote the code that for the behavior with the fake paragraph. This fixed some bugs and improved the behavior in general.
1. Don't create fake paragraph near with textblocks.
2. Fixed error, that's occurred with node-selection and `after`-direction
3. Add _waterfall_ fake-paragraphs behaviour. For example, cursor in `doc -> blockquote -> yfm_cut -> yfm_note -> blockquote`. On first `down` press fake paragraph will be created in `yfm_note`, then in `yfm_cut`, then in `blockquote`, and then in `doc`
=> feat(Selection, Cursor)!: rewrite code for fake-paragraph behaviour

src/extensions/behavior/Clipboard/clipboard.ts, src/extensions/behavior/Clipboard/utils.ts
There is a problem when users paste content that was copied from browser and which contains markup.
Added a function that checks if pasted html has only divs and spans on higher level that don't have classname and contain only text content. Than it extracts text from it and processes as regular markup
=> feat: get markup from html that has only text

src/core/markdown/MarkdownParser.ts, src/core/types/parser.ts, src/extensions/markdown/CodeBlock/CodeBlock.test.ts, src/extensions/markdown/CodeBlock/CodeBlockSpecs/index.ts
1. Remove extra new line at the end of content of code and fence blocks
2. Always add new line to node.textContent of codeblock when serializing
=> fix(CodeBlock): fix parsing and serialization of code and fence blocks

src/core/markdown/MarkdownSerializer.js, src/extensions/markdown/Subscript/Subscript.test.ts, src/extensions/markdown/Subscript/SubscriptSpecs/index.ts, src/extensions/markdown/Superscript/Superscript.test.ts, src/extensions/markdown/Superscript/SuperscriptSpecs/index.ts
`markdown-it-sup` and `markdown-it-sub` is based on [pandoc](https://pandoc.org/MANUAL.html#superscripts-and-subscripts) definition:
> The text between `^...^` or `~...~` may not contain spaces or newlines.
> ...
> if you want the letter P with ‘a cat’ in subscripts, use `P~a\ cat~`, not `P~a cat~`.
=> fix: escape whitespaces within superscript and subscript

src/extensions/yfm/Color/Color.test.ts, src/extensions/yfm/Color/ColorSpecs/index.ts, src/extensions/yfm/Color/index.ts, src/extensions/yfm/Color/utils.ts, src/extensions/yfm/specs.ts
Parse spans with `(md|yfm)-colorify--{color}` class names
Parse spans with style `"color:<color>"`
=> feat(Color): add parseDOM rules to specs

src/extensions/base/BaseStyles/index.scss, src/extensions/behavior/Selection/selection.scss
Outline should be set only if ProseMirror is focused.
=> fix: selected node styles appear only if ProseMirror is focused

src/extensions/yfm/YfmCut/plugins/auto-open.ts
When you start dragging and hovering over the closed YfmCut, it will automatically open after 500 ms
=> feat(YfmCut): auto-opening yfm-cut when dragging over it

package.json, src/extensions/behavior/ReactRenderer/index.ts, src/pm/commands.ts, src/pm/history.ts, src/pm/inputrules.ts, src/pm/keymap.ts, src/pm/model.ts, src/pm/readme.md, src/pm/state.ts, src/pm/transform.ts, src/pm/utils.ts, src/pm/view.ts, src/styles/markdown.scss
Adds `exports` and `typesVersions` to `package.json`.
Also adds `/pm` submodule, that re-export `prosemirror` modules
=> feat: add package exports

package-lock.json, package.json
`markdown-it-attrs` is in deps in `@diplodoc/transform`
But we use attrs plugin directly in _core_, so it should be in deps
=> fix(deps): add markdown-it-attrs to deps

src/extensions/yfm/YfmCut/actions/toYfmCut.ts
- create an open yfm-cut
- move cursor to title of created yfm-cut
- move nodes between selections to content of create yfm-cut
=> feat(YfmCut): improve the behavior when creating yfm-cut

src/extensions/yfm/Checkbox/actions.ts, src/utils/inputrules.ts
New behavior of inserting checkbox:
- Disabled:
- when selecting any text
- when cursor inside complex textblock (exclude checkboxes)
- selection type is some other then TextSelection or NodeSelection
- If cursor is in paragraph: replace current paragraph with checkbox with contents of paragraph
- If node selection or if cursor is in another textblock or checkbox: insert new checkbox after current node, and move cursor inside new checkbox
=> feat(Checkbox): improve checkbox insertion

src/extensions/markdown/Link/Link.test.ts, src/extensions/markdown/Link/LinkSpecs/index.ts
Markdown-it incorrectly parses links with unbalanced parentheses in URLs.
This is fixed by escaping the parentheses.
=> fix(Link): ascape parentheses in link url

demo/PMSelection.tsx, demo/Playground.tsx, demo/ProseMirrorDevTools.tsx, demo/editor-in-editor/EditorInEditorExtension/index.tsx, demo/editor-in-editor/index.tsx, src/bundle/Editor.ts, src/bundle/MarkdownEditorView.tsx, src/bundle/MarkupEditorView.tsx, src/bundle/ToolbarView.tsx, src/bundle/WysiwygEditorView.tsx, src/bundle/index.ts, src/bundle/settings/index.tsx, src/bundle/useMarkdownEditor.ts
Renamed:
- type `MarkdownEditorType` ––> `MarkdownEditorMode`
- event name `editor.on('change-editor-type', ...)` ––> `editor.on('change-editor-mode', ...)`
- field of type `ToolbarActionData['editorType']` ––> `ToolbarActionData['editorMode']`
- field of interface `Editor.currentType` ––> `Editor.currentMode`
- method of interface `Editor.setEditorType(...)` ––> `Editor.setEditorMode(...)`
- prop of `useMarkdownEditor` hook: `initialEditorType` ––> `initialEditorMode`
=> feat(bundle)!: rename editorType ––> editorMode

package.json, src/cm/autocomplete.ts, src/cm/commands.ts, src/cm/language.ts, src/cm/readme.md, src/cm/state.ts, src/cm/view.ts, src/pm/readme.md
Added submodule `@gravity-ui/markdown-editor/cm/*` with re-export of core codemirror modules
=> feat: add re-export of codemirror core modules

demo/PresetDemo.tsx, demo/Presets.stories.tsx, src/bundle/Editor.ts, src/bundle/MarkdownEditorView.tsx, src/bundle/MarkupEditorView.tsx, src/bundle/config/markup.tsx, src/bundle/config/wysiwyg.ts, src/bundle/index.ts, src/bundle/useMarkdownEditor.ts, src/bundle/wysiwyg-preset.ts, src/core/Editor.ts, src/core/ExtensionsManager.ts, src/extensions/behavior/SelectionContext/index.ts
Added `preset` prop to `useMarkdownEditor` hook.\
The preset specifies a set of plug-in extensions.\
Preset value can be `'zero' | 'commonmark' | 'default' | 'yfm' | 'full'`.
`'zero' | 'commonmark' | 'default'` – includes functionality similar to the markdown-it presets.\
`'yfm'` – YFM functionality
`'full'` – previously default functionality
Default value – `'full'`
=> feat: add editor presets

package.json
Added `@gravity-ui/markdown-editor/i18n` submodule, which exports an instance of `i18n` and function `registerKeyset`.
This can be useful for packages with editor extensions.
=> feat: add i18n submodule

src/extensions/yfm/YfmTable/plugins/YfmTableControls/yfmTableCellView.tsx
In some cases, an error occurred when creating nodeView for table cell. I fixed it.
In addition, I optimized nodeView render for those cases when the controls will not be rendered
=> fix(YfmTable): fix runtime error in table cell nodeView

src/core/markdown/MarkdownSerializer.js, src/extensions/markdown/Lists/Lists.test.ts, src/extensions/markdown/Lists/ListsSpecs/const.ts, src/extensions/markdown/Lists/ListsSpecs/index.ts, src/extensions/markdown/Lists/ListsSpecs/parser.ts, src/extensions/markdown/Lists/ListsSpecs/schema.ts, src/extensions/markdown/Lists/ListsSpecs/serializer.ts, src/extensions/markdown/Lists/index.ts, src/extensions/markdown/Lists/inputrules.ts, src/extensions/markdown/Lists/plugins/MergeListsPlugin.test.ts
Before: bullet-lists are always serialized using `*`
Now: preserve bullets (`*`|`-`|`+`)
=> fix(Lists): preserve markup of list items

src/extensions/yfm/YfmHeading/YfmHeadingSpecs/const.ts, src/extensions/yfm/YfmHeading/YfmHeadingSpecs/index.ts, src/extensions/yfm/YfmHeading/YfmHeadingSpecs/utils.ts, src/extensions/yfm/YfmHeading/commands.ts
=> feat(YfmHeading): support folding attribute

demo/Playground.tsx, package-lock.json, package.json, src/extensions/yfm/YfmHtmlBlock/YfmHtmlBlockNodeView/NodeView.tsx, src/extensions/yfm/YfmHtmlBlock/YfmHtmlBlockNodeView/YfmHtmlBlockView.tsx, src/extensions/yfm/YfmHtmlBlock/utils.test.ts, src/extensions/yfm/YfmHtmlBlock/utils.ts
1) added an option for YfmHTMLBlock editing mode with default styles and links.
2) expanded the CSS whitelist with properties gap and line-height.
3) added the sanitize helper.
=> fix(YfmHtmlBlock): added YfmHtmlBlockOptions

src/extensions/yfm/YfmTable/YfmTableSpecs/serializer.ts
For some broken cases, were prosemirror document contains rows with cells without outer table and tbody
=> fix(YfmTable): revert serialization logic for yfm-table row and cell

src/extensions/yfm/YfmTable/plugins/YfmTableControls/view.scss
<details>
<summary>Before fix</summary>
</details>
<details>
<summary>After fix</summary>
</details>
Also fixed control buttons' offsets and sizes
=> fix(YfmTable): fix border style for tbody

src/extensions/markdown/Lists/Lists.test.ts, src/extensions/markdown/Lists/ListsSpecs/const.ts, src/extensions/markdown/Lists/ListsSpecs/parser.ts, src/extensions/markdown/Lists/ListsSpecs/schema.ts, src/extensions/markdown/Lists/ListsSpecs/serializer.ts, src/extensions/markdown/Lists/plugins/MergeListsPlugin.test.ts
When switch ordered_list –> bullet_list (or vice versa), the list items are serialized with incorrect markup.
This change fix it.
=> fix(Lists): check that list items are being serialized with correct markup

demo/Playground.tsx, demo/RememberMode.stories.tsx, src/bundle/Editor.ts, src/bundle/MarkdownEditorView.tsx, src/bundle/MarkupEditorView.tsx, src/bundle/ToolbarView.tsx, src/bundle/config/markup.tsx, src/bundle/config/wysiwyg.ts, src/bundle/index.ts, src/bundle/settings/index.tsx, src/bundle/types.ts, src/bundle/useMarkdownEditor.ts, src/bundle/wysiwyg-preset.ts, src/core/Editor.ts, src/markup/codemirror/index.ts, src/markup/codemirror/search-plugin/plugin.ts
Preparation to major #423
Scopes of options:
- `md` – markdown parser options
- `initial` – initial values
- `handlers` – various handlers
- `experimental` – experimental features
- `markup` – configuration of markup mode
- `wysiwyg` – configuration of wysiwyg mode
=> feat(bundle): group editor settings by scope

src/bundle/useMarkdownEditor.ts
`useMarkdownEditor()`: Take file upload handler from `props.handlers.uploadFile` with fallback from `props.fileUploadHandler`
=> fix(bundle): file upload handler is not passed in wysiwyg mode

package-lock.json, package.json
Although this is minor update of markdown-it-attrs, it contains only  a fix: arve0/markdown-it-attrs#155
=> fix(deps): sync version of markdown-it-attrs with @diplodoc/transform

demo/components/Playground.tsx, demo/components/PlaygroundMini.tsx, demo/defaults/args.ts, demo/defaults/md-plugins.ts, demo/stories/markdown/Markdown.stories.tsx, package-lock.json, package.json, src/bundle/Editor.ts, src/bundle/MarkdownEditorView.tsx, src/bundle/SplitModeView.tsx, src/bundle/types.ts, src/bundle/useMarkdownEditor.ts, src/bundle/wysiwyg-preset.ts, src/extensions/yfm/YfmCut/YfmCut.test.ts, src/extensions/yfm/YfmCut/YfmCutSpecs/const.ts, src/extensions/yfm/YfmCut/YfmCutSpecs/index.ts, src/extensions/yfm/YfmCut/YfmCutSpecs/parser.ts, src/extensions/yfm/YfmCut/YfmCutSpecs/schema.ts, src/extensions/yfm/YfmCut/YfmCutSpecs/serializer.ts, src/index.ts, src/markup/codemirror/create.ts, src/markup/codemirror/directive-facet.ts, src/markup/codemirror/index.ts, src/markup/codemirror/yfm.ts, src/markup/commands/yfm.ts, src/utils/directive.ts, src/utils/index.ts, tests/sameMarkup.ts, tests/toMatchNode.ts
- added `directiveSyntax` experiment. It can be accessed from `builder.context` for wysiwyg extensions, and via state facet in markup mode.
- added support for directive syntax for YfmCut. See syntax example here: diplodoc-platform/cut-extension#22
=> feat(YfmCut): support directive syntax

src/bundle/config/markup.tsx, src/bundle/config/wysiwyg.ts
While standardizing the code, I discovered that these components are present in the WYSIWYG editor but missing in the markup. They might need to be added in the future. 
```
- wGptItemData
- wToggleHeadingFoldingItemData
- wTextItemData
- wCommandMenuConfig
- wCommandMenuConfigByPreset
- wSelectionMenuConfig
- wSelectionMenuConfigByPreset
```
I also added aliases in the markup to ensure consistency with the naming in WYSIWYG.
=> refactor(toolbar): grouped toolbar elements by type, assembled configs without nesting

src/extensions/behavior/Cursor/gapcursor.ts, src/extensions/behavior/Cursor/index.ts
Old behavior: when cursor has been emulated by GapCursorSelection, inputRules incorrect handling text input.
Now: GapCursorSelection will be replaced with empty textblock, and after that inputRules run his handling. So now they are correct handle user input.
Old behavior: when cursor was emulated using GapCursorSelection, inputRules handled text input incorrectly.
Now: first, the GapCursorSelection will be replaced with an empty textblock, and after that the inputRules will run their handler. So now they are correctly handling user input.
=> fix(Cursor): input-rules does not work when cursor in virtual selection (GapCursorSelection)

demo/components/Playground.tsx, demo/components/PlaygroundLayout.tsx, demo/components/PlaygroundMini.tsx, demo/defaults/excluded-controls.ts, demo/hooks/useMarkdownEditorValue.ts, demo/stories/css-variables/CSSVariables.tsx, demo/stories/editor-in-editor/EditorInEditor.tsx, demo/stories/escape-config/EscapeConfig.stories.tsx, demo/stories/escape-config/EscapeConfig.tsx, demo/stories/experiments/empty-row/EmptyRow.stories.tsx, demo/stories/experiments/empty-row/EmptyRows.tsx, demo/stories/ghost/Ghost.tsx, demo/stories/gpt/GPT.tsx, package-lock.json
For `demo` only:
1. Added PlaygroundLayout component
2. Added `useMarkdownEditorValue()` hook
3. Rewritten `CustomCSSVariables`, `EditorInEditor`, `EscapeConfig`, `Ghost`, `GPT` stories
4. Added new story – `PreserveEmptyRows`
=> chore(demo): added new story; rewritten some other stories

src/extensions/markdown/Link/LinkSpecs/index.ts
There are two link syntaxes: `<link>` and `[text](url)`
Due to the fact that other marks can be applied to the text, we consider `[text](url)` to be the default syntax for links in WYSIWYG-mode.
Serialization rule: if there are no other marks on link and `text==urls`, then use the short syntax `<link>`. If one of the conditions is not met, then we use the full syntax `[text](url)` as resistant to use with other marks. At the same time, priority of link mark should be higher than that of all other marks.
=> fix(Link): set high priority to link mark

src/extensions/base/BaseSchema/BaseSchemaSpecs/index.ts
Fixed an issue where a space in a string was not recognized as an empty string, and therefore the "&nbsp;" was not added to the markup. This problem could occur when copying rendered markup to the editor.
Before:
After
=> fix(BaseSchema): fixed definition of an empty string during serialization

package.json
Remove `typesVersions` from `package.json` because [TypeScript starting from v4.7 fully supports `exports` field](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing).
Also `./bundle` and `./bundle/*` are removed from `exports`.
=> feat(package)!: drop typesVersions and improve exports

src/utils/nodes.test.ts
Added tests to check the isNodeEmpty function,
we check with an empty paragraph, with a non-empty paragraph, and with another block
=> test: add tests for isNodeEmpty function

src/core/SerializerTokensRegistry.test.ts, src/core/markdown/Markdown.test.ts, src/core/markdown/MarkdownSerializer.ts, src/core/types/serializer.ts, src/extensions/additional/GPT/gptExtension/view.tsx, src/extensions/base/BaseSchema/BaseSchemaSpecs/index.ts, src/extensions/behavior/Clipboard/clipboard.ts, src/extensions/markdown/CodeBlock/commands.ts, src/extensions/markdown/Link/LinkSpecs/index.ts
**BREAKING CHANGE**: Updated SerializerMarkToken — parent parameter in open and close changed from Fragment to Node.
=> feat(types)!: updated MarkdownSerializer types

src/extensions/yfm/YfmCut/index.scss
After updates in [cut-extension@171da43](https://github.com/diplodoc-platform/cut-extension/commit/171da43b970d08afde5411a602ab11fba4bc76ac) and [markdown-editor#591](https://github.com/gravity-ui/markdown-editor/pull/591), cut styles changed, causing incongruity. This fix adjusts `translateX(-50%)` for arrow positioning.
=> fix(YfmCut): fixed open state styles

src/view/hooks/useYfmShowElemWithId/useYfmShowElemWithId.ts
After updates in [cut-extension@171da43](https://github.com/diplodoc-platform/cut-extension/commit/171da43b970d08afde5411a602ab11fba4bc76ac) and https://github.com/gravity-ui/markdown-editor/pull/591, cut open logic changed
=> fix(view): updated cut open logic to use attrs instead of classes

src/extensions/yfm/ImgSize/ImageWidget/index.ts, src/extensions/yfm/ImgSize/ImageWidget/widget.tsx, src/extensions/yfm/ImgSize/index.ts
The `enableNewImageSizeCalculation` option was added in PR #451 to set image width and height.  This PR extends support to `ImageWidget`.
=> fix(ImgSize): support enableNewImageSizeCalculation in ImageWidget

jest.config.js
Added aliases to `tsconfig.json` in [#656](https://github.com/gravity-ui/markdown-editor/pull/656/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0), requiring matching updates in `jest.config.js`. Used `pathsToModuleNameMapper` to sync aliases (`#core`, `#cm/*`, etc.) for Jest, fixing test failures.
=> test: support import aliases

src/extensions/markdown/Lists/index.ts, src/extensions/markdown/Lists/plugins/CollapseListsPlugin.test.ts, src/extensions/markdown/Lists/plugins/CollapseListsPlugin.ts
Added a plugin for the WYSIWYG editor that extracts nested lists from empty list items and merges them into the parent list. If a list item contains only a nested list, it is moved up and integrated into the structure. The document structure remains clean and readable, ensuring correct indentation and hierarchy.
**Before:**
```md
* * Nested item
```
after:
```md
* Nested item
```
before:
```md
* First item
* * Nested item
Paragraph
* Second item
```
after:
```md
* First item
* Nested item
* Paragraph
* Second item
```
https://github.com/user-attachments/assets/86aea7bf-a209-4d10-bfcb-55ba8c10d8e3
=> feat(Lists): improved collapsing of empty list items with nested lists

src/extensions/additional/YfmHtmlBlock/utils.ts, src/extensions/markdown/Lists/plugins/CollapseListsPlugin.ts
Fixed issues with default sanitize import in ESM projects by supporting sanitize named export, keeping default import for compatibility. See https://github.com/diplodoc-platform/transform/releases/tag/v4.47.4
=> feat(YfmHtmlBlock): added compatibility for sanitize named export

demo/stories/gpt/gptWidgetOptions.tsx, src/extensions/additional/GPT/MarkupGpt/plugin.ts
they sent the problem that the onClose method does not work in the plugin in markup mode, it turned out that it was not used in the plugin for markup mode.
=> fix(gpt): added "onClose" props in plugin for  markup mode

src/extensions/markdown/CodeBlock/CodeBlockHighlight/CodeBlockHighlight.ts
Upgrading to v15 broke `require` in `CodeBlockHighlight` for `highlight.js` and `lowlight` (ESM) with `ReferenceError: require is not defined`. This PR switches to `async import` for proper loading of optional deps while keeping ProseMirror sync API compatibility.
=> fix(CodeBlock): resolved async import loading for CodeBlockHighlight

src/extensions/behavior/Autocomplete/index.ts, src/extensions/behavior/Autocomplete/types.ts, src/extensions/behavior/Autocomplete/utils.ts, src/extensions/behavior/CommandMenu/handler.ts, src/extensions/behavior/index.ts, src/extensions/yfm/Emoji/EmojiSuggest/EmojiHandler.ts
In collaborative editing, when the first user opens suggest and the second user edits the document to the point where suggest opened, the suggest handler contains an outdated range of the start and end points of the suggestion
This PR fixes this: suggest handlers now always get the actual range from the autocomplete state when an element is selected
=> fix: get actual range when selecting item in suggests (command menu, emoji suggest)

demo/components/Playground.scss, src/bundle/MarkupEditorView.scss, src/bundle/settings/index.scss, src/bundle/toolbar/ToolbarButtonWithPopupMenu.scss, src/extensions/additional/FoldingHeading/plugins/folding.scss, src/extensions/behavior/CommandMenu/component.scss, src/extensions/yfm/Emoji/EmojiSuggest/EmojiSuggestComponent.scss, src/extensions/yfm/ImgSize/ImageWidget/view.scss, src/extensions/yfm/YfmCut/index.scss, src/extensions/yfm/YfmTabs/index.scss, src/forms/base/FormRow.scss, src/markup/codemirror/files-upload-plugin/widget.scss, src/styles/markdown copy.scss, src/styles/markdown.scss, src/styles/styles.scss
Fixes #595
As of Dart Sass `1.80.0`, `@import` is deprecated and will be removed in `3.0.0`.  `@use` is now the recommended approach for compatibility with future versions and build tools. More details: [Sass Documentation](https://sass-lang.com/documentation/at-rules/import/)
=> build: replaced import with use in scss files due  deprecation

demo/components/Playground.tsx, demo/components/PlaygroundMini.tsx, demo/components/SplitModePreview.tsx, demo/defaults/args.ts, demo/stories/yfm/content.ts, package-lock.json, package.json, src/extensions/additional/YfmHtmlBlock/YfmHtmlBlockNodeView/YfmHtmlBlockView.tsx, src/view/hocs/withYfmHtml/index.tsx, src/view/hocs/withYfmHtml/useYfmHtmlBlockRuntime.ts
Implemented the `disabledModes` prop in `htmlRuntimeConfig` to disable specific HTML block runtime modes (e.g., shadow mode), offering improved runtime customization.
=> feat(view): added option to control HTML block runtimes

src/extensions/behavior/Clipboard/code.ts, src/extensions/behavior/Clipboard/index.ts
Added additional handler for pasting into code block or code mark. It executes before all other paste handlers.
=> fix(Clipboard): correct handling of pasting into code

demo/components/Playground.tsx, demo/components/PlaygroundMini.tsx, demo/components/SplitModePreview.tsx, demo/defaults/args.ts, demo/stories/playground/Playground.stories.tsx, demo/stories/presets/Preset.tsx, package-lock.json, package.json, src/bundle/types.ts, src/bundle/useMarkdownEditor.ts, src/bundle/wysiwyg-preset.ts, src/extensions/yfm/YfmConfigs/YfmConfigsSpecs/index.ts, src/extensions/yfm/YfmHeading/YfmHeading.test.ts, src/extensions/yfm/YfmHeading/YfmHeadingSpecs/index.ts, src/extensions/yfm/YfmHeading/YfmHeadingSpecs/markdown/heading-attrs.ts
Since `markdown-it-attrs` will be disabled by default in `@diplodoc/transform` in the future, see diplodoc-platform/diplodoc#45
=> feat(wysiwyg): allow to disable `markdown-it-attrs` in yfm preset

src/bundle/config/w-heading-config.tsx, src/bundle/toolbar/utils/toolbarsConfigs.ts, src/modules/toolbars/items.tsx, src/modules/toolbars/types.ts, src/toolbar/ToolbarListButton.tsx, src/toolbar/types.ts
| Before | After |
|--------|--------|
| <img width="400" alt="Screenshot 2025-03-28 at 14 35 42" src="https://github.com/user-attachments/assets/d42dc6f3-f1fe-43c4-a931-becf90985bed" /> | <img width="400" alt="Screenshot 2025-03-28 at 14 35 49" src="https://github.com/user-attachments/assets/d2aab9b7-8824-4bdc-b5d3-48ec23136236" /> |
=> feat(toolbar): show current heading level in editor toolbar

src/extensions/markdown/Superscript/SuperscriptSpecs/index.ts, src/extensions/yfm/ImgSize/ImgSizeSpecs/index.ts, src/extensions/yfm/Monospace/MonospaceSpecs/index.ts, src/extensions/yfm/Video/VideoSpecs/index.ts, src/extensions/yfm/YfmNote/YfmNoteSpecs/index.ts, src/extensions/yfm/YfmTable/YfmTableSpecs/index.ts
Used named import instead of default to fix log func issues in ESM environments.
like in https://github.com/gravity-ui/markdown-editor/pull/668
=> fix: resolved log func via named import to avoid default mismatch

src/extensions/markdown/Lists/commands.ts
Previously, the `sinkOnlySelectedListItem` command returned false without dispatch, causing toolbar buttons like `sinkListItem` to be incorrectly disabled even when the action could be applied. Changed the return value to true, ensuring that toolbar buttons correctly reflect the availability of the sink action based on the document state.
=> fix(Lists): fixed toolbar button activation for sink list item

src/extensions/yfm/YfmNote/commands.test.ts, src/extensions/yfm/YfmNote/commands.ts
Due to the appearance of the noteContent container in the yfm_note structure, when deleting via Backspace, an extra wrapper used to remain; now we insert the contents of this container directly instead, without an additional level.
If the note body was empty, Backspace did nothing - now, with empty content, the cursor goes to the end of the heading.
=> fix(YfmNote): improved note removal on Backspace

src/extensions/markdown/CodeBlock/CodeBlockHighlight/CodeBlockHighlight.ts
Fixes https://github.com/gravity-ui/markdown-editor/issues/813
=> fix(CodeBlock): skip lang init on import fail

demo/components/Playground.tsx, demo/components/PlaygroundMini.tsx, demo/defaults/args.ts, demo/stories/playground/Playground.stories.tsx, src/bundle/toolbar/ToolbarButtonWithPopupMenu.tsx, src/bundle/toolbar/custom/ToolbarColors.tsx
Fixed warnings:
```
react-dom.development.js:86 Warning: Invalid value for prop `exec` on <button> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
at button
at Button (http://localhost:8888/vendors-node_modules_gravity-ui_uikit_build_esm_index_js-node_modules_gravity-ui_uikit_build_-7fc4e1.iframe.bundle.js:11741:13)
at Tooltip (http://localhost:8888/vendors-node_modules_gravity-ui_uikit_build_esm_index_js-node_modules_gravity-ui_uikit_build_-7fc4e1.iframe.bundle.js:24083:20)
at ActionTooltip (http://localhost:8888/vendors-node_modules_gravity-ui_uikit_build_esm_index_js-node_modules_gravity-ui_uikit_build_-7fc4e1.iframe.bundle.js:9986:26)
at ToolbarButtonWithPopupMenu …
```
=> fix(bundle): dont pass invalid props to dom in ToolbarColors component
