src/extensions/yfm/Math/view-and-edit.ts
src/toolbar/ToolbarListButton.scss
src/toolbar/ToolbarListButton.tsx
src/toolbar/types.ts

you can now add hints in toolbar config that will be rendered as uikit HelpPopover

feat: hints

---

src/extensions/behavior/Placeholder/index.scss
src/extensions/behavior/Placeholder/index.ts

1. fix display of fake cursor before placeholder
2. show fake cursor before placeholder in all browsers

fix(Placeholder): fix display of fake cursor before placeholder

---

package-lock.json
package.json
src/toolbar/FlexToolbar.tsx
src/toolbar/ToolbarButton.tsx
src/toolbar/ToolbarListButton.tsx
src/toolbar/const.ts
src/toolbar/index.ts

Add tooltip for items with a drop-down list of actions.
Add delay before open and close tooltip.

feat(tooltip): add tooltip to list items

---

src/selection.d.ts
src/utils/selection.ts

solving problem when instanceof doesn't work in webpack production build for selection

feat: added new field for selection interface

---

src/extensions/behavior/Selection/commands.ts
src/extensions/yfm/YfmTable/commands/goToNextRow.ts
src/extensions/yfm/YfmTable/index.ts
src/table-utils/utils.ts
src/utils/selection.ts

Navigation between table rows with keyboard arrow keys

feat: switching table rows when pressing up and down arrow keys on keyboard

---

src/extensions/markdown/Lists/commands.test.ts
src/extensions/markdown/Lists/commands.ts
src/extensions/markdown/Lists/index.ts
src/utils/selection.ts
tests/setup.ts

Lifting a list item and breaking the list when the cursor is at the beginning of the list item and the Backspace button has been pressed

feat(Lists): breaking the list when deleting a list item

---

src/extensions/behavior/Clipboard/clipboard.ts

For _copy_ and _cut_ events: add HTML and text of selected fragment to clipboard (default behavior), and add to clipboard serialized markup of selected fragment

feat(Clipboard): insert markup, html and text of the selected fragment into the clipboard

---

demo/HtmlPreview.tsx
demo/Playground.stories.tsx
demo/Playground.tsx
package-lock.json
package.json
src/core/Editor.ts
src/core/ExtensionsManager.ts
src/react/useYfmEditor.ts

Add `linkifyTlds` parameter like in yandex-cloud/yfm-transform#191

feat: add support to linkify urls with custom tlds

---

src/extensions/behavior/Clipboard/clipboard.ts

Case: copying several paragraphs from table cell (or from blockquote)
Before: copied the table with one cell (or blockquote) with selected paragraphs
Now: copied only selected paragraphs

feat(Clipboard): smarter copying

---

src/extensions/yfm/Math/commands.ts
src/extensions/yfm/Math/const.ts
src/extensions/yfm/Math/index.scss
src/extensions/yfm/Math/index.ts
src/extensions/yfm/Math/view-and-edit.scss
src/extensions/yfm/Math/view-and-edit.ts

improved UX when working with an inline math

feat(Math): improve UX with inline math

---

src/extensions/behavior/Placeholder/index.ts

Previously, decorations were created with each state update. In some cases, this led to an error

fix(Placeholder): create new decorations on every EditorProps.decorations() call

---

src/extensions/markdown/CodeBlock/index.ts

Added functionality that serializes content of selection and adding it to codeblock when codeblock is created

feat: serialization of selection content when creating codeblock

---

src/extensions/behavior/Placeholder/index.ts

As stated in [prosemirror documentation](https://prosemirror.net/docs/guide/#view.decorations) if you have a lot of decorations to render (as in large empty tables) you should not recreate a decoration set for every document update, but rather keep it in plugin state and manage it's mapping and adding/removing of decorations when plugin applies it's state

fix: optimisation for large tables

---

src/commands/join.test.ts
src/commands/join.ts
src/extensions/markdown/Blockquote/BlockquoteSpecs/index.ts
src/extensions/markdown/Blockquote/commands.ts
src/extensions/markdown/Blockquote/const.ts
src/extensions/markdown/Lists/commands.test.ts
src/extensions/markdown/Lists/commands.ts
src/extensions/markdown/Lists/index.ts
src/extensions/markdown/Lists/utils.ts
src/utils/selection.ts

Similar to the behavior with blockquotes #90

feat(Lists): support for joining the previous list

---

README.md

chore(readme): fix ci status badge

---

package-lock.json
package.json

Also updated `@bem-react/classname` and `@gravity-ui/i18n`

feat(deps): support @doc-tools/transform@3

---

src/extensions/yfm/YfmTabs/YfmTabsSpecs/spec.ts
src/extensions/yfm/YfmTabs/actions.ts
src/extensions/yfm/YfmTabs/index.ts

Added action for tabs creation

feat: tabs action

---

package-lock.json
package.json
src/extensions/yfm/YfmTabs/YfmTabs.test.ts
src/extensions/yfm/YfmTabs/YfmTabsSpecs/const.ts
src/extensions/yfm/YfmTabs/YfmTabsSpecs/spec.ts
src/extensions/yfm/YfmTabs/index.scss
src/extensions/yfm/YfmTabs/plugins.ts

Reverts yandex-cloud/yfm-editor#118

Revert "upd: @doc-tools/transform"

---

.github/workflows/ci.yml
package-lock.json
package.json
tests/esbuild-test/esbuild-tester.js
tests/esbuild-test/esbuild-to-test.mjs

Added a test to track [ambiguous exports](https://github.com/evanw/esbuild/issues/716) in case this package is used with esbuild.

Add esbuild compatability test

---

src/extensions/yfm/ImgSize/index.ts

Removed ambiguous export of ImgSizeAttr

fix: remove ambiguous export

---

src/extensions/base/BaseSchema/BaseSchemaSpecs/index.ts
src/extensions/behavior/Placeholder/index.ts
src/extensions/behavior/index.ts
src/extensions/markdown/Deflist/DeflistSpecs/index.ts
src/extensions/markdown/Deflist/DeflistSpecs/spec.ts
src/extensions/markdown/Heading/HeadingSpecs/index.ts
src/extensions/yfm/Checkbox/CheckboxSpecs/index.ts
src/extensions/yfm/Checkbox/CheckboxSpecs/spec.ts
src/extensions/yfm/ImgSize/ImgSizeSpecs/index.ts
src/extensions/yfm/YfmCut/YfmCutSpecs/index.ts
src/extensions/yfm/YfmCut/YfmCutSpecs/spec.ts
src/extensions/yfm/YfmHeading/YfmHeadingSpecs/index.ts
src/extensions/yfm/YfmNote/YfmNoteSpecs/index.ts
src/extensions/yfm/YfmNote/YfmNoteSpecs/spec.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/index.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/spec.ts
src/extensions/yfm/YfmTabs/YfmTabsSpecs/index.ts
src/extensions/yfm/YfmTabs/YfmTabsSpecs/spec.ts
src/utils/placeholder.ts

Add options for placeholders that will be passed in extensions.

feat: add options for placeholders

---

src/extensions/markdown/HorizontalRule/index.ts

The behavior of inserting horizontal line:
- Disabled:
- when selecting any text
- when cursor inside complex textblock
- selection type is some other then TextSelection or NodeSelection
- If node selection: replace the selected node with horizontal_rule
- If cursor is in an empty paragraph: insert horizontal_rule before current paragraph
- If cursor is in another textblock or a non-empty paragraph: insert horizontal_rule and a new empty paragraph after the current textblock

feat(HorizontalRule): improve horizontal line insertion

---

package-lock.json
package.json

- Change package name to `@gravity-ui/markdown-editor`
- Update package.json with actual info

feat!: change package name

---

.storybook/preview.ts
demo/Markdown.stories.tsx
demo/PlaygroundEditorInEditor.stories.tsx
demo/YFM.stories.tsx
demo/utils/preview.tsx

Added stories showing individual features of the editor

docs(demo): add more stories to storybook playground

---

demo/Playground.tsx
demo/RememberMode.stories.tsx

added "Remember the mode" story

added "Remember the mode" story

---

package-lock.json
package.json
src/extensions/yfm/Checkbox/CheckboxSpecs/index.ts
src/extensions/yfm/YfmTable/YfmTable.test.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/const.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/parser.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/schema.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/serializer.ts
src/extensions/yfm/YfmTable/plugins/YfmTableControls/yfmTableCellView.tsx
src/extensions/yfm/YfmTabs/YfmTabs.test.ts

See more info in diplodoc docs: [Cell Merging](https://diplodoc.com/docs/en/syntax/tables/multiline#span) and [Text Alignment in Cells](https://diplodoc.com/docs/en/syntax/tables/multiline#text-alignment-in-cells)

feat(YfmTable): added support of colspan, rowspan and cell-align in yfm-tables

---

src/extensions/yfm/YfmHtmlBlock/utils.test.ts
src/extensions/yfm/YfmHtmlBlock/utils.ts

expanded the white list of css properties of the html block
current blacklist
```
whiteList['alignment-adjust'] = false; // default: auto
whiteList['alignment-baseline'] = false; // default: baseline
whiteList['anchor-point'] = false; // default: none
whiteList['animation'] = false; // default: depending on individual properties
whiteList['animation-delay'] = false; // default: 0
whiteList['animation-direction'] = false; // default: normal
whiteList['animation-duration'] = false; // default: 0
whiteList['animation-fill-mode'] = false; // default: none
whiteList['animation-iteration-count'] = false; // default: 1
whiteList['animation-name'] = false; // default: none
whiteList['animation-play-state'] = false; // default: running
whiteList['animation-timing-function'] = false; // default: …
```

feat(yfmHtmlBlock): updated css white list

---

src/extensions/behavior/SelectionContext/index.ts

In some cases, the selection tooltip was not shown. This change fixes the problem.

fix(SelectionContext): save editor state when start to select content with mouse

---

demo/playground/Playground.tsx
demo/presets/PresetDemo.tsx
demo/utils/imageUrl.ts
src/bundle/wysiwyg-preset.ts
src/extensions/markdown/Image/imageUrlPaste/index.ts
src/extensions/markdown/Image/index.ts
src/extensions/yfm/ImgSize/ImagePaste/index.ts
src/extensions/yfm/ImgSize/index.ts
src/presets/commonmark.ts

Added the functionality for converting pasted urls to images

feat(Image): convert pasted image urls to images

---

demo/css-variables/CSSVariables.stories.tsx
demo/css-variables/CSSVariablesDemo.tsx
docs/how-to-customize-the-editor.md
src/bundle/MarkupEditorView.scss
src/bundle/WysiwygEditorView.scss
src/bundle/sticky/sticky.scss

add padding variables for toolbar and editor content
add custom css variables story and documentation

feat(EditorView): add padding variables

---

src/extensions/yfm/Checkbox/CheckboxSpecs/const.ts
src/extensions/yfm/Checkbox/CheckboxSpecs/index.ts
src/extensions/yfm/Checkbox/CheckboxSpecs/schema.ts
src/extensions/yfm/Checkbox/CheckboxSpecs/serializer.ts
src/extensions/yfm/Checkbox/const.ts
src/extensions/yfm/Checkbox/index.ts
src/extensions/yfm/Checkbox/nodeviews.ts

In collaborative mode checked status of checkbox was not updated. I'm fixed this by correct handling checkbox click and correct updating node-view of checkbox input node.

fix(Checkbox): correct handling of checkbox click

---

package-lock.json
package.json

More details on [discuss.codemirror.net](https://discuss.codemirror.net/t/the-editor-freezes-when-using-markdown-and-large-text/8752)

fix(deps): bumped @lezer/markdown to fix large text hang

---

src/extensions/markdown/Link/paste-plugin.ts

In some cases, when link was copied from HTML or another view, it was pasted as plain text. This change fixed this

fix(Link): fixed pasting link to empty selection

---

src/bundle/Editor.ts

fix(bundle): fixed imports with relative paths

---

src/markup/codemirror/search-plugin/plugin.ts
src/markup/codemirror/search-plugin/view/SearchPopup.tsx

When searching inside the markup editor, the search tooltip did not display the current search status. This PR fixed it.

fix(markup): show initial search state in search popup

---

package-lock.json
package.json
src/extensions/yfm/Video/VideoSpecs/index.ts

1. updated `@diplodoc/transform` to v4.43.0
2. updated `@diplodoc/cut-extension`  to v0.6.1
3. removed deprecated properties in `VideoSpec`
4. moved `@diplodoc/file-extension` to peer deps

feat(deps): updated @diplodoc/transform and related packages

---

src/bundle/config/markup.tsx
src/bundle/config/wysiwyg.ts
src/bundle/toolbar/ToolbarButtonWithPopupMenu.tsx
src/bundle/toolbar/ToolbarSelect.tsx
src/bundle/toolbar/markup/MToolbarColors.tsx
src/bundle/toolbar/markup/MToolbarFilePopup.tsx
src/bundle/toolbar/markup/MToolbarImagePopup.tsx
src/bundle/toolbar/types.ts
src/bundle/toolbar/wysiwyg/WToolbarColors.tsx
src/bundle/toolbar/wysiwyg/WToolbarTextSelect.tsx

Added and exported types `WToolbarBaseProps` and `MToolbarBaseProps`

fix(bundle): added missing toolbar types

---

demo/stories/examples/img-custom-form/ImageCustomForm.stories.tsx
demo/stories/examples/img-custom-form/ImageCustomForm.tsx
src/extensions/yfm/ImgSize/ImageWidget/index.ts
src/extensions/yfm/ImgSize/ImageWidget/view.tsx
src/extensions/yfm/ImgSize/ImageWidget/widget.tsx
src/extensions/yfm/ImgSize/index.ts

See `Examples / Custom Image Widget` page in storybook
For #624

feat(ImgSize): added ability to render custom form in image widget

---

src/extensions/additional/YfmHtmlBlock/utils.test.ts
src/extensions/additional/YfmHtmlBlock/utils.ts
src/extensions/markdown/Deflist/DeflistSpecs/index.ts
src/extensions/markdown/Html/schema.ts
src/extensions/markdown/Superscript/SuperscriptSpecs/index.ts
src/extensions/yfm/Checkbox/CheckboxSpecs/index.ts
src/extensions/yfm/ImgSize/ImgSizeSpecs/const.ts
src/extensions/yfm/ImgSize/ImgSizeSpecs/index.ts
src/extensions/yfm/Monospace/MonospaceSpecs/index.ts
src/extensions/yfm/Video/VideoSpecs/index.ts
src/extensions/yfm/Video/VideoSpecs/md-video.ts
src/extensions/yfm/YfmConfigs/index.ts
src/extensions/yfm/YfmNote/YfmNoteSpecs/index.ts
src/extensions/yfm/YfmTable/YfmTableSpecs/index.ts
src/extensions/yfm/YfmTabs/actions.ts
src/extensions/yfm/YfmTabs/plugins.ts
src/markdown-it/emoji.ts

ESModules requires extension in import path

fix: added file extensions to full-path imports for esm-build

---

src/extensions/yfm/Emoji/EmojiSpecs/EmojiSpecs.ts

fix(Emoji): added file extension to plugin import path

---

docs/how-to-add-visual-test.md
tests/playwright/core/helpers.ts
tests/playwright/core/index.ts
tests/playwright/core/types.ts

1. Added debug helpers
2. Updated test documentation with details about 
– helpers;
– clipboard usage;
– click handling specifics.

test: added debug helpers

---

docs/how-to-add-visual-test.md
src/bundle/MarkupEditorComponent.tsx
src/bundle/MarkupEditorView.tsx
src/bundle/ToolbarView.tsx
src/bundle/WysiwygEditorComponent.tsx
src/bundle/WysiwygEditorView.tsx
src/bundle/settings/index.tsx
src/extensions/behavior/CommandMenu/component.tsx
src/extensions/markdown/Link/PlaceholderWidget/widget.tsx
src/toolbar/FlexToolbar.tsx
src/toolbar/ToolbarButton.tsx
src/toolbar/ToolbarListButton.tsx
src/toolbar/types.ts
src/view/components/YfmHtml/YfmStaticView.tsx
tests/playwright/core/actions.ts
tests/playwright/core/editor.ts
tests/playwright/core/index.ts
tests/playwright/core/types.ts
tests/playwright/core/wait.ts
tests/visual-tests/playground/Cut.visual.test.tsx
tests/visual-tests/playground/Link.visual.test.tsx

- Updated `editor` locators methods  
- Added reusable `actions`  
- Extended `wait` helpers  
- Improved QA attributes for test stability  
- Documented locator selection rules for editor testing  
- Added popup tests for:
- WYSIWYG: command menu (`/`), link  
- Markup: character input patterns

test(core): added actions, updated editor and wait methods

---

src/extensions/additional/GPT/constants.ts

I liked the hot "key command shift y" not found conflicts associated with him in the browsers Safari and Yandex Google

feat(Gpt): changed hotkey to open gpt popup

---

src/forms/TextInput.tsx

fix: correct TextAreaFixed display name
